Main application/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "demo#index"

  get '/deploy', to: 'demo#timeline'
  get '/distribution', to: 'demo#prototype'
  get '/download', to: 'demo#download'  
end

Main application/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Main application/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Main application/app/controllers/demo_controller.rb
class DemoController < ApplicationController
    def signUp
    end

    def deploy
    end

    def distribution
    end


    def download
    end
end

Main application/app/helpers/application_helper.rb
module ApplicationHelper
end

Main application/app/helpers/demo_helper.rb
module DemoHelper
end

Main application/app/views/demo/_footer.html.erb
  <footer class="footer has-background-success">
      <div class="content has-text-centered has-text-white">
        <h1>EcoCleanJa</h1>
        <div class="columns">
          <div class="column">
            <h6>About Us</h6>
            <p class="has-text-center"> A young, vibrant team with the stong desire to live in a cleaner environment and who have been empowered to make it happen.
            </p>
          </div>
          <div class="column">
            <h6>Affilates</h6>
            <ul>
              <li><a href="#">"Nuh Dutty up Jamaica"</a></li>
              <li><a href="#">Ministry of Local Government</a></li>
              <li><a href="#">National Solid Waste Management Authority (NSWMA)</a></li>
              <li><a href="#">Garbage Disposal & Sanitation Systems Ltd.</a></li>
            </ul>
          </div>
          <div class="column">
            <h6>Our Presence</h6>
            <ul>
              <li><a href="#">Calendar of events</a></li>
              <li><a href="#">Commumity based activities</a></li>

            </ul>
          </div>
          <div class="column">
            <h6>Stay in the loop</h6>
            <div class="control has-icons-left has-icons-right">
              <input class="input is-medium" type="email" placeholder="Email">
              <span class="icon is-left">
              <i class="fa fa-envelope"></i>
              </span>
            </div>
            <a class="button is-success is-rounded">Subscribe</a>
          </div>
        </div>
      </div>
    </footer>
    <div class="has-background-success has-text-white bottom mt-4">
      <div class="container is-fluid">
        <div class="columns">
          <div class="column">
            <p>EcoCleanJa 2021</p>
          </div>
          <div class="column has-text-right">
            <i class="fa fa-facebook-square"></i>
            <i class="fa fa-twitter-square"></i>
            <i class="fa fa-google-plus-square"></i>
            <i class="fa fa-linkedin-square"></i>
          </div>
        </div>
      </div>
    </div>

Main application/app/views/demo/_navbar.html.erb
  <div class="container">
    <div id="navMenu" class="navbar-menu">
      <div class="navbar-start">

        <%= link_to  root_path, class: "navbar-item" do%>
          <%= image_tag 'EcoClean logo and text.png' %>
        <% end %>
 

      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to 'Timeline', deploy_path, class: "button is-dark" %>
          <a href="https://report-distribution.herokuapp.com/" target="blank" class= "button is-dark">Reports Distribution</a>
            <%= link_to 'Download', download_path, class: "button is-dark" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

Main application/app/views/demo/download.html.erb
<%= render 'navbar' %>

<section class="hero is-success is-fullheight-with-navbar mb-4">
  <div class="hero-body">
    <p class="title is-1">
      Visit The Playstore or Appstore to Download the EcoCleanJa App!
    </p>
  </div>
</section>


<%= render 'footer' %>

Main application/app/views/demo/index.html.erb
<%= render 'navbar' %>

<section class="hero is-succes is-fullheight-with-navbar landing mb-4">
  <div class="hero-body">
    <p class="title is-1 has-text-dark ">
      EcoCleanJa! <br> The solution to Jamaica's <br> Garbage Collection Problem
    </p>
  </div>
</section>


<div class="is-divider" data-content="-"></div>


<section class="hero is-medium is-success">
    <div class="hero-body">
    <p class="title">
     Why is a smart collection system needed in Jamaica?
    </p>
    <p class="subtitle content is-large">
      A collection system is needed so that authorities can provide a timely response to dynamic waste disposal  issues reported by citizens.
    </p>
  </div>
</section>

<%# Tiles %>

<div class="tile is-ancestor">
  <div class="tile is-vertical is-12">


    <%# Sign up page %>

    <div class="tile">

          <div class="tile is-parent">
        <article class="tile is-child notification is-info">
          <p class="title">Main screen</p>
          <%# <p class="subtitle">With an image</p> %>
          <figure class="image is-3by5">
            <%= image_tag 'main-bg-rem.png' %>
            <%# <img src="/assets/main-bg-rem.png"> %>
          </figure>
        </article>
      </div>

      <div class="tile is-parent is-vertical">

        <article class="tile is-child notification is-primary">
          <p class="title">Simple easy to use application</p>
          <br>
          <p class="subtitle content is-large">
          Users can sign up by using an email address, icloud or google account.
          <br>
          <br>
          Unique usernames are assigned and used for the submission of all report.
          <br>
          <br>
          Submiting anonymous reports obscures one's username.
          </p>
            
        </article>

        <article class="tile is-child notification  is-success">
          <p class="title">Visually appealing design</p>
          <br>
          <p class="subtitle content is-large">The material design and palatable colours make the application user friendly. <br><br> The dark theme is also a part of the modern trend it mobile and web application development. <br><br> In further releases accessibility functionality will be added for the blind.</p>
        </article>
      </div>
    </div>

    <%# 2nd tile set REPORT %>
    <div class="tile">



      <div class="tile is-parent is-vertical">
      
        <article class="tile is-child notification is-primary">
          <p class="title">Submit a report</p>
          <br>
          <p class="subtitle content is-large">Reports made by the residents are directly transmitted to the authorities. <br><br>These texts are analysed at a dedicated help desk. <br><br>Additionally, image submission are analysed using to ascertain the severity of the pile up. </p>
        </article>

        <article class="tile is-child notification  is-success">
          <p class="title">Details of submission</p>
          <br>
          <p class="subtitle content is-large">Submissions may include photos and also any pertinent text, geolocation is embedded by default for each submission. <br><br>Once a submission is made it is reflected in the profile of that user. </p>
        </article>
      </div>

      <div class="tile is-parent">
        <article class="tile is-child notification is-info">
          <p class="title">Report an Issue</p>
          <%# <p class="subtitle">With an image</p> %>
          <figure class="image is-3by5">
            <%= image_tag 'report.png' %>
          </figure>
        </article>
      </div>

    </div>


  <%# 1st tile set FORUM%>


    <div class="tile">
      <div class="tile is-parent">
        <article class="tile is-child notification is-info">
          <p class="title">Forum</p>
          <%# <p class="subtitle">With an image</p> %>
          <figure class="image is-3by5">
          <%= image_tag 'dis-edited.png' %>
          </figure>
        </article>
      </div>

      <div class="tile is-parent is-vertical">

        <article class="tile is-child notification is-primary">
          <p class="title">Discussion Forum</p>
          <br>
          <p class="subtitle content is-large">Where everyone can discuss the issues that they are facing as it regards garbage collection with the authorites. <br><br> They can also discuss combined efforts that are being made to mitigate illegal dumping activities. <br><br> This integrates with a strong neighbourhood watch program, where the collective good is superlative to the individual.</p>
        </article>

        <article class="tile is-child notification  is-primary">
          <p class="title">Explaination of issues</p>
          <br>
          <p class="subtitle content is-large">The authorites can use this medium to have 'town hall' discussion to see how best they can continue to serve. <br><br>This is especially helpful for issues that are common or repeated.  </p>
        </article>
      </div>



    </div>

    <%# Report page %>

    <div class="tile">
      <div class="tile is-parent is-vertical">

        <article class="tile is-child notification is-primary">
          <p class="title">View Report</p>
          <br>
          <p class="subtitle content is-large">A user can see their reports and that of other users. <br><br> They can also use this to see solutions or work-arounds that have been proposed to increase efficiency for specific use case. </p>
        </article>

        <article class="tile is-child notification  is-primary">
          <p class="title">Edit Report</p>
          <br>
          <p class="subtitle content is-large">For an issue that a specific user has reported, the option exists for a limited time to update the report made. <br><br> This prevents the user from unknowingly submit inaccurate, incomplete report.</p>
        </article>
      </div>

      <div class="tile is-parent">
        <article class="tile is-child notification is-info">
          <p class="title">Report</p>
          <%# <p class="subtitle">With an image</p> %>
          <figure class="image is-3by5">
          <%= image_tag 'details-edited.png' %>
          </figure>
        </article>
      </div>
    </div>


    <%# Live chat page  %>

    <div class="tile">

      <div class="tile is-parent">
        <article class="tile is-child notification is-info">
          <p class="title">Direct contact with collectors</p>
          <figure class="image is-3by5">
          <%= image_tag 'CHAT-removebg-preview.png' %>
          </figure>
        </article>
      </div>

      <div class="tile is-parent is-vertical">

        <article class="tile is-child notification is-primary">
          <p class="title">Clarification</p>
          <br>
          <p class="subtitle content is-large">The collection entites can contact a user who submitted a report directly to have clarity on the issue. <br><br>This helps the collectors obtain additional information on a report made, and also to boost customer satisfaction. </p>
        </article>

        <article class="tile is-child notification  is-success">
          <p class="title">Engagement</p>
          <br>
          <p class="subtitle content is-large">Communication over this form fosters a healthy relationship between the public and collectors.</p>
        </article>
      </div>


    </div>

    <%# illegal Dumping %>


    <div class="tile">
      <div class="tile is-parent is-vertical">

        <article class="tile is-child notification is-primary">
          <p class="title">Anonymous Reporting</p>
          <br>
          <p class="subtitle content is-large">The option is available for users to make a confidential report about suspecious activites. <br><br>This helps the break the cycle of 'snitches must die' in Jamaica and help to reveal the perpetrators. </p>
        </article>

        <article class="tile is-child notification  is-success">
          <p class="title">Anonymity</p>
          <br>
          <p class="subtitle content is-large">A confidential report means  that a user's login information is neither used nor stored
          upon making such a request. <br><br>It is important that the user be as clear as possible, since the authorites will
          have no means of following up with them.</p>
        </article>
      </div>

      <div class="tile is-parent">
        <article class="tile is-child notification is-info">
          <p class="title">Report suspicious disposal</p>
          <%# <p class="subtitle">With an image</p> %>
          <figure class="image is-3by5">
          <%= image_tag 'illegal-removebg-preview.png' %>
          </figure>
        </article>
      </div>
    </div>

  </div>

</div>

<section class="hero is-large is-success">
    <div class="hero-body">
    <p class="title">
      How does it all work behind the scenes?
    </p>
    <p class="subtitle content is-large">
      The solution leaverages a variety of technologies. This includes geo-spatial technologies <br>
      such as geo-fencing, geo-rereferencing(GPS) machine learning and statistical analysis.

    </p>
  </div>
</section>


<section>
  <div class="tile is-ancestor">

    <div class="tile is-vertical is-12">
      

      <div class="tile">
        <div class="tile is-parent">
          <article class="tile is-child notification is-info">
            <p class="title">Area designated with the use of Geo-fencing</p>
            <p class="subtitle">This enables a predefined area operation for a set of trucks, see interaction below</p>
            <figure class="">
              <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1JWmWVnfJmDJX2dMXEdl0hQV1QKrLQ3AM&ehbc=2E312F" width="640" height="480"></iframe>
            </figure>
          </article>
        </div>

        <div class="tile is-parent is-vertical">
          <article class="tile is-child notification is-primary">
            <p class="title">What is geo-fencing? </p>
            <br>
            <p class="subtitle content is-large">
            Geo-fencing is a feature in a software program that uses GPS
              to define geographical boundaries.</p>
          </article>
          <article class="tile is-child notification is-primary">
            <p class="title">Why is it important? </p>
            <br>
            <p class="subtitle content is-large">

                It creates a modular approach to collection of waste as the areas are dynamic in nature
                changing based on the AI's design. 
        
            </p>
          </article>
        </div>

      </div>
  </div>

</section>



<section>
  <div class="tile is-ancestor">
    <div class="tile is-vertical is-12">
      <div class="tile">



        <div class="tile is-parent is-vertical">
          <article class="tile is-child notification is-primary">
            <p class="title">What's in the Dashboard?</p>
            <br>
            <p class="subtitle content is-large">
              The Dashboard consists of all the information that the system posseses and can be reported as a metric. </p>
          </article>
          <article class="tile is-child notification is-primary">
            <p class="title">Why is it important?</p>
            <br>
            <p class="subtitle content is-large">
            The information collected is pimarily used to foster machine learning to prioritise pick-up location and plan routes. 
            </p>
          </article>
        </div>

        <div class="tile is-parent">
          <article class="tile is-child notification is-info">
            <p class="title">Collection agent's Dashboard</p> 
            <p class="subtitle">The main view of behind the scenes.</p>
            <figure class="">
            <%= image_tag 'dashboard1_edited.png' %>
            </figure>
          </article>
        </div>


      </div>
  </div>

</section>


<section>
  <div class="tile is-ancestor">
    <div class="tile is-vertical is-12">
      <div class="tile">


        <div class="tile is-parent">
          <article class="tile is-child notification is-info">
            <p class="title">Auxillary Metrics</p>
            <p class="subtitle">Supplimentary information</p>
            <figure class="">
            <%= image_tag 'dashboard2.png' %>
            </figure>
          </article>
        </div>

        <div class="tile is-parent is-vertical">
          <article class="tile is-child notification is-primary">
            <p class="title">Auxillary Metrics</p>
            <br>
            <p class="subtitle content is-large">
              This section of the Dashboard discusses information that in not a functional requirement. None the less pertinent.</p>
          </article>
          <article class="tile is-child notification is-success">
            <p class="title">Why is it important?</p>
            <br>
            <p class="subtitle content is-large">
              This section help the collection agent to see how EcoCleanJa is impacting the business that it has integrated with.
            </p>
          </article>
        </div>


      </div>
  </div>

</section>


<section class="hero is-medium is-primary my-4">
    <div class="hero-body">
    <p class="title">
      What Are you Wait for? <br>
      Visit the appstore or playstore and download the app today and contribute to a cleaner Jamaica!
    </p>

  </div>
</section>

<%# FOOTER %>
<%= render 'footer' %>

Main application/app/views/demo/timeline.html.erb
<%= render 'navbar' %>

<section>
<p class="title is-2 has-text-centered"> Project Timeline</p>
</section>

<section>
<div class="container is-fluid">
  <figure class="image is-16by9">
    <iframe class="has-ratio"  src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQYZs4HU4yc_WxqgT8U7YzI0E8TVbRg_vzj8WqpKtMzMHye_78WqpmYKN48EjFzmNhrXNCpOO_WqMk6/pubhtml?widget=true&amp;headers=false"></iframe>
  </figure>
</div>


</section>

<%= render 'footer' %>

Main application/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcoCleanJa</title>
    <%= favicon_link_tag 'favicon.ico'%>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>

    <%= yield %>
  </body>
</html>